[project]
name = "kagglecomps"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "category-encoders>=2.9.0",
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "lightgbm>=4.6.0",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "optuna>=4.9.0",
    "pandas>=3.0.3",
    "polars>=1.42.1",
    "safetensors>=0.8.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "tabfm[jax,pytorch]",
    "xgboost>=3.3.0",
]

[tool.uv.sources]
tabfm = { git = "https://github.com/google-research/tabfm.git" }
